### ISSUE TITLE
Android sample is incomplete

### ISSUE THREAD

**Issue by bagza** [getsentry/examples#16]
Please, provide a sample of using your sentry android gradle plugin

The only sentry stuff in configuration is just a compile dependency of sentry sdk.

**Comment by marandaneto** [comment]
hey @bagza I've just updated the Android sample to our brand new Android SDK, please check it out.
also the code has the sentry android gradle plugin configuration, it's commented though otherwise compile will fail, just uncomment it and fill the content in the `sentry.properties` file :)
let us know if you find any issues.

#40

Thanks :)
